### ISSUE TITLE
You could replace this with <a> element

### ISSUE THREAD

**Issue by Bear-Coding** [facn6/week1ch#24]
Why would you need a function to handle this?
Did you try to put the buttons in <a> element with a navigation to the ID of the other elements? :recycle:

https://github.com/facn6/week1ch/blob/d384accaeb5dc0d23df686211e30ea290a95eb87/index.html#L40-L44

**Comment by kira-abl** [comment]
Yes, you are right, it was made for a bad reason, now it is fixed. The problem was we did not know how to make the button text not look like a link.
